/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * 
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user guide at https://docs.gradle.org/5.0/userguide/multi_project_builds.html
 */

rootProject.name = "db-toolchain"

// https://github.com/gradle/gradle/issues/5816
// include("xslt20-stylesheets", "xslt20-resources")

// https://docs.gradle.org/current/userguide/composite_builds.html
includeBuild("xslt20-stylesheets")
includeBuild("xslt20-resources")
// includeBuild("xslt20-java")
