/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.aanno.dbtoolchain;

import com.github.aanno.dbtoolchain.xml.S9ApiSingleton;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        S9ApiSingleton.getInstance();
    }
}
