/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.aanno.dbtoolchain;

import org.testng.annotations.*;
import static org.testng.Assert.*;
import com.github.aanno.dbtoolchain.App;

public class Xslt2ExampleTest {
    @Test public void appHasAGreeting() {
        Xslt2Example classUnderTest = new Xslt2Example();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
